import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { readingService } from '../../services';

// Async thunks
export const fetchReadings = createAsyncThunk(
  'readings/fetchAll',
  async (_, { rejectWithValue }) => {
    try {
      const data = await readingService.getAllReadings();
      return data;
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || 'Failed to fetch readings');
    }
  }
);

export const fetchReadingsByMeterId = createAsyncThunk(
  'readings/fetchByMeterId',
  async (meterId, { rejectWithValue }) => {
    try {
      const data = await readingService.getReadingsByMeterId(meterId);
      return data;
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || 'Failed to fetch meter readings');
    }
  }
);

export const fetchLastReading = createAsyncThunk(
  'readings/fetchLast',
  async (meterId, { rejectWithValue }) => {
    try {
      const data = await readingService.getLastReading(meterId);
      return data;
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || 'Failed to fetch last reading');
    }
  }
);

export const createReading = createAsyncThunk(
  'readings/create',
  async (readingData, { rejectWithValue }) => {
    try {
      const data = await readingService.createReading(readingData);
      return data;
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || 'Failed to create reading');
    }
  }
);

export const updateReading = createAsyncThunk(
  'readings/update',
  async ({ id, data }, { rejectWithValue }) => {
    try {
      const response = await readingService.updateReading(id, data);
      return response;
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || 'Failed to update reading');
    }
  }
);

export const deleteReading = createAsyncThunk(
  'readings/delete',
  async (id, { rejectWithValue }) => {
    try {
      await readingService.deleteReading(id);
      return id;
    } catch (error) {
      return rejectWithValue(error.response?.data?.message || 'Failed to delete reading');
    }
  }
);

// Initial state
const initialState = {
  readings: [],
  currentReading: null,
  lastReading: null,
  isLoading: false,
  error: null,
  success: false,
  billGenerated: false
};

// Slice
const readingSlice = createSlice({
  name: 'readings',
  initialState,
  reducers: {
    clearError: (state) => {
      state.error = null;
    },
    clearSuccess: (state) => {
      state.success = false;
      state.billGenerated = false;
    },
    clearCurrentReading: (state) => {
      state.currentReading = null;
    }
  },
  extraReducers: (builder) => {
    builder
      // Fetch all readings
      .addCase(fetchReadings.pending, (state) => {
        state.isLoading = true;
        state.error = null;
      })
      .addCase(fetchReadings.fulfilled, (state, action) => {
        state.isLoading = false;
        state.readings = action.payload.data || action.payload;
        state.error = null;
      })
      .addCase(fetchReadings.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload;
      })
      // Fetch readings by meter ID
      .addCase(fetchReadingsByMeterId.pending, (state) => {
        state.isLoading = true;
        state.error = null;
      })
      .addCase(fetchReadingsByMeterId.fulfilled, (state, action) => {
        state.isLoading = false;
        state.readings = action.payload.data || action.payload;
        state.error = null;
      })
      .addCase(fetchReadingsByMeterId.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload;
      })
      // Fetch last reading
      .addCase(fetchLastReading.pending, (state) => {
        state.isLoading = true;
        state.error = null;
      })
      .addCase(fetchLastReading.fulfilled, (state, action) => {
        state.isLoading = false;
        state.lastReading = action.payload.data || action.payload;
        state.error = null;
      })
      .addCase(fetchLastReading.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload;
      })
      // Create reading (triggers bill generation)
      .addCase(createReading.pending, (state) => {
        state.isLoading = true;
        state.error = null;
        state.success = false;
        state.billGenerated = false;
      })
      .addCase(createReading.fulfilled, (state, action) => {
        state.isLoading = false;
        // Don't push incomplete data - let fetchReadings handle it
        state.success = true;
        state.billGenerated = true; // Bill auto-generated by database trigger
        state.error = null;
      })
      .addCase(createReading.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload;
        state.success = false;
        state.billGenerated = false;
      })
      // Update reading
      .addCase(updateReading.pending, (state) => {
        state.isLoading = true;
        state.error = null;
        state.success = false;
      })
      .addCase(updateReading.fulfilled, (state, action) => {
        state.isLoading = false;
        const index = state.readings.findIndex(r => r.ReadingID === action.payload.data?.ReadingID);
        if (index !== -1) {
          state.readings[index] = action.payload.data;
        }
        state.success = true;
        state.error = null;
      })
      .addCase(updateReading.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload;
        state.success = false;
      })
      // Delete reading
      .addCase(deleteReading.pending, (state) => {
        state.isLoading = true;
        state.error = null;
        state.success = false;
      })
      .addCase(deleteReading.fulfilled, (state, action) => {
        state.isLoading = false;
        state.readings = state.readings.filter(r => r.ReadingID !== action.payload);
        state.success = true;
        state.error = null;
      })
      .addCase(deleteReading.rejected, (state, action) => {
        state.isLoading = false;
        state.error = action.payload;
        state.success = false;
      });
  }
});

export const { clearError, clearSuccess, clearCurrentReading } = readingSlice.actions;
export default readingSlice.reducer;
